[package]
name = "crosstream"
version = "0.1.0"
edition = "2024"

[features]
zerocopy = ["dep:zerocopy"]
bytemuck = ["dep:bytemuck"]

[dependencies]
# For allocating off-heap memory.
memmap2 = "0.9"

# For byte to record transmutations.
zerocopy = { version = "0.8", optional = true, features = ["derive"] }
bytemuck = { version = "1.23", optional = true, features = [
    "derive",
    "must_cast",
    "min_const_generics",
] }

# For nicer error handling.
thiserror = "2.0"

[dev-dependencies]
# For property based tests.
bolero = "0.13"

# For parameterized tests.
rstest = "0.26"
